### PR TITLE
Python bindings

### PR DESCRIPTION
**Pull request by marcelm**
This wasn’t on the roadmap, but while I considered how to implement supplementary alignments and alignment of long reads, I thought that I would like to play around with the algorithms for NAM finding and alignment and that this would be much nicer in Python.

This is totally unfinished, but this snippet shows off what can be done:
```python
#!/usr/bin/env python3
import sys
sys.path[:0] = ["build"]

import pystrobealign as sa

# Open references FASTA and populate index
refs = sa.References.from_fasta("tests/phix.fasta")
index_parameters = sa.IndexParameters.from_read_length(100)
index = sa.StrobemerIndex(refs, index_parameters)
index.populate()

# Find NAMs for a single query sequence
query = "TGCGTTTATGGTACGCTGGACTTTGTGGGATACCCTCGCTTTCCTGCTCCTGTTGAGTTTATTGCTGCCG"
randstrobes = sa.randstrobes_query(query, index_parameters)
for nam in sa.find_nams(randstrobes, index):
    ref = refs[nam.ref_index].sequence
    ref_aligned = ref[nam.ref_start:nam.ref_end]
    query_aligned = query[nam.query_start:nam.query_end]
    print(query_aligned, "matches", ref_aligned, "score", nam.score)
```
result:
```
TATGGTACGCTGGACTTTGTGGGATACCCTCGCTTTCCTGCTCCTGTTGAGTTTATTGC matches TATGGTACGCTGGACTTTGTGGGATACCCTCGCTTTCCTGCTCCTGTTGAGTTTATTGC score 354.0
TTATGGTACGCTGGACTTTGTGGGATACC matches CGCTTTCCTGCTCCTGTTGAGTTTATTGC score 29.0
TGGTACGCTGGACTTTGTGGGATACCCTCGCTT matches ATACCCTCGCTTTCCTGCTCCTGTTGAGTTTAT score 33.0
TTTGTGGGATACCCTCGCTTTCCTGCTCCTGTTGAG matches CGCTGGACTTTGTGGGATACCCTCGCTTTCCTGCTC score 36.0
GGGATACCCTCGCTTTCCTGCTCCTGTTGAGTTTATTG matches TATGGTACGCTGGACTTTGTGGGATACCCTCGCTTTCC score 38.0
```

This uses [nanobind](https://nanobind.readthedocs.io/en/latest/), which took some reading to learn, but allows for very concise binding code and is actually nice to use once you get the hang of it.

### CODE REVIEW

**Comment by ksahlin** [comment]
I haven't had the time to test this out, but it looks really great!

**Comment by marcelm** [comment]
I didn’t give any instructions on how to build this, so testing would have been hard. I pushed an update now so that the bindings can be installed with `pip install .` (copying a lot from https://github.com/mitsuba-renderer/nanogui/).

With that, the `sys.path[:0] = ["build"]` line is no longer necessary. Also, it is now `import strobealign` (not `pystrobealign`). But take your time, this is more of a side thing.

**Comment by marcelm** [comment]
I think this is ready to be merged if this is something you would like to have for strobealign. While the bindings are incomplete, should have some docstrings and possibly more tests, they do work already and have been useful in my experiments recently. I think it would be good to have them in `main` so that the bindings are built as part of the tests, which would ensure that any future changes don’t break them.

**Comment by ksahlin** [comment]
Sounds good to me! do you have a small example with some code e.g. of how you produced one of the plots that you showed me? The example you posted originally helps a lot, but there are probably some other components such as ref/query coordinates, is_rc, etc that are used? (the actual plotting may not be necessary, just how you arrived at the data)

**Comment by marcelm** [comment]
Ok, so as I alluded, this is "beta quality", but let’s merge it so it doesn’t bit rot.

**Pull request merged**
