### PR TITLE
Turn -i into a flag and add --use-index option

### PR DESCRIPTION
**Pull request by marcelm**
- When `-i` is specified, write the index to reference path + `.sti`
- When --use-index is specified, read the index from reference path + `.sti`
- If `-i` is used and one or two reads files are provided, estimate read length from the reads
- Do not write the reference sequences to the index (read them from the FASTA instead)
- Write a "magic number" as the first four bytes to the index file so that we can be somewhat sure that it actually is a strobemer index when reading it in again.

## To Do 

- [x] Log message "Total time creating strobemers" is printed even with `--use-index`

See #115

### CODE REVIEW

**Comment by ksahlin** [comment]
I agree also with the To-Do of Log message "Total time creating strobemers". If this message is consistent among settings it will be convenient in mapping runtime analysis because the message can be reg-exp'ed and subtracted in both settings from the total runtime.

**Comment by marcelm** [comment]
> I agree also with the To-Do of Log message "Total time creating strobemers".

Now I’m not sure I understand. To elaborate: The message 'Total time creating strobemers' is printed even when the option `--use-index` is used (and I don’t know at the moment what it is measuring), but IMO it should not be printed. Instead, a message that says 'Total time creating strobemers' should be printed. But we can also change this to read "Total time creating/reading strobemers" or something like this so that it is the same in both cases.

**Comment by ksahlin** [comment]
My mistake, I mixed it up with  "Total time indexing". 

Also, it is a super easy tweak to use whatever unique timing log message for the benchmarking. So ignore my comment in full. Currently I am looking for "Total time indexing:" (all-in-one) or "Total time reading index:" (pre-generated index) when subtracting index time from map time.

**Comment by marcelm** [comment]
Alright, I think the messages look ok now from what I can tell. At some point, I want to go through those logging messages and make them a bit nicer somehow, and I’ll review them more at that time.

**Pull request merged**
