### PR TITLE
Introduce an end bonus to penalize soft-clipping

### LINKED ISSUE #54: Very short soft-clipped ends
All the reads in the phiX test dataset happen to start with a single `N` base (an artifact of picking the first 100 reads from the run and not random ones). For a read that otherwise matches without errors, StrobeAlign reports the alignment as `1S300=`.

I found this to be unexpected because BWA-MEM reports this as `301M` (with the `N` considered to be a mismatch as one can see from the `MD` tag). BWA-MEM penalizes soft-clipping (option `-L`) with a default penalty of 5, so it’ll prefer (at most) one mismatch (penalty 4) over soft clipping.

On the other hand, minimap2 also soft clips and reports `1S300M`.

I think that penalizing soft clipping is beneficial when aligning short reads. It is not important for shotgun sequencing, but for targeted sequencing (amplicons), soft clipping single bases introduces a bias: Any variation at that position in the reference cannot be observed. For minimap2, it’s not so important because it is primarily (AFAIK) for longer reads.

This is probably not a high-priority issue, but I wanted to at least write it down because I was suprised when inspecting the test BAM output.

### PR DESCRIPTION
**Pull request by marcelm**
An alternative to #247 that is independent of the WFA2/ksw2 alignment restructuring in #242.

Closes #54

~~I’m not happy with how single-end accuracy (using the simpler "1/0" overlap metric) decreases at 50 bp (-0.1 percentage points, in bold in the table) and will need to investigate, but everything else looks ok or actually quite good.~~ This was a bug, see comment below.

**Tables updated on 2023-03-01 for commit ee34340**

## Single ends, Jaccard overlap

Average difference: 0.14565

dataset | main | this PR | diff
-|-|-|-|
drosophila/1x50-1M | 81.66 | 81.969 | 0.309
drosophila/1x100-1M | 88.882 | 89.064 | 0.182
drosophila/1x150-1M | 90.657 | 90.781 | 0.124
drosophila/1x200-1M | 91.743 | 91.837 | 0.094
drosophila/1x300-1M | 93.063 | 93.126 | 0.063
CHM13/1x50-1M | 80.771 | 81.092 | 0.321
CHM13/1x100-1M | 90.236 | 90.419 | 0.183
CHM13/1x150-1M | 92.118 | 92.244 | 0.126
CHM13/1x200-1M | 92.995 | 93.09 | 0.095
CHM13/1x300-1M | 93.988 | 94.051 | 0.063
rye/1x50-1M | 44.156 | 44.381 | 0.225
rye/1x100-1M | 68.961 | 69.13 | 0.169
rye/1x150-1M | 80.102 | 80.224 | 0.122
rye/1x200-1M | 85.579 | 85.669 | 0.09
rye/1x300-1M | 90.173 | 90.232 | 0.059
maize/1x50-1M | 46.91 | 47.144 | 0.234
maize/1x100-1M | 70.222 | 70.399 | 0.177
maize/1x150-1M | 80.936 | 81.059 | 0.123
maize/1x200-1M | 86.497 | 86.59 | 0.093
maize/1x300-1M | 91.706 | 91.767 | 0.061

## Paired ends, Jaccard overlap

Average difference: 0.1553

dataset | main | this PR | diff
-|-|-|-|
drosophila/2x50-1M | 89.603 | 89.927 | 0.324
drosophila/2x100-1M | 92.05 | 92.24 | 0.19
drosophila/2x150-1M | 92.961 | 93.084 | 0.123
drosophila/2x200-1M | 93.293 | 93.392 | 0.099
drosophila/2x300-1M | 95.203 | 95.268 | 0.065
CHM13/2x50-1M | 90.0 | 90.317 | 0.317
CHM13/2x100-1M | 92.891 | 93.073 | 0.182
CHM13/2x150-1M | 93.868 | 94.0 | 0.132
CHM13/2x200-1M | 94.201 | 94.297 | 0.096
CHM13/2x300-1M | 95.464 | 95.527 | 0.063
rye/2x50-1M | 68.458 | 68.755 | 0.297
rye/2x100-1M | 85.191 | 85.37 | 0.179
rye/2x150-1M | 89.871 | 89.982 | 0.111
rye/2x200-1M | 91.141 | 91.232 | 0.091
rye/2x300-1M | 94.242 | 94.299 | 0.057
maize/2x50-1M | 70.841 | 71.159 | 0.318
maize/2x100-1M | 86.804 | 86.988 | 0.184
maize/2x150-1M | 91.431 | 91.558 | 0.127
maize/2x200-1M | 92.709 | 92.794 | 0.085
maize/2x300-1M | 96.556 | 96.622 | 0.066

## Single ends, 1/0 overlap

Average difference: 0.015895

dataset | main | this PR | diff
-|-|-|-|
drosophila/1x50-1M | 82.0217 | 82.033 | 0.0113
drosophila/1x100-1M | 89.1824 | 89.1891 | 0.0067
drosophila/1x150-1M | 90.904 | 90.9077 | 0.0037
drosophila/1x200-1M | 91.9516 | 91.9535 | 0.0019
drosophila/1x300-1M | 93.2247 | 93.2254 | 0.0007
CHM13/1x50-1M | 81.1337 | 81.1605 | 0.0268
CHM13/1x100-1M | 90.5432 | 90.5476 | 0.0044
CHM13/1x150-1M | 92.3735 | 92.3761 | 0.0026
CHM13/1x200-1M | 93.2063 | 93.2074 | 0.0011
CHM13/1x300-1M | 94.1502 | 94.1505 | 0.0003
rye/1x50-1M | 44.3501 | 44.4244 | 0.0743
rye/1x100-1M | 69.2219 | 69.2576 | 0.0357
rye/1x150-1M | 80.3844 | 80.3999 | 0.0155
rye/1x200-1M | 85.8692 | 85.8734 | 0.0042
rye/1x300-1M | 90.4895 | 90.4879 | -0.0016
maize/1x50-1M | 47.1051 | 47.1744 | 0.0693
maize/1x100-1M | 70.4435 | 70.483 | 0.0395
maize/1x150-1M | 81.1458 | 81.1613 | 0.0155
maize/1x200-1M | 86.6858 | 86.6911 | 0.0053
maize/1x300-1M | 91.858 | 91.8587 | 0.0007

## Paired ends, 1/0 overlap

Average difference: 0.010865

dataset | main | this PR | diff
-|-|-|-|
drosophila/2x50-1M | 90.0643 | 90.07735 | 0.01305
drosophila/2x100-1M | 92.38105 | 92.3898 | 0.00875
drosophila/2x150-1M | 93.2202 | 93.21915 | -0.00105
drosophila/2x200-1M | 93.506 | 93.5103 | 0.0043
drosophila/2x300-1M | 95.3651 | 95.36705 | 0.00195
CHM13/2x50-1M | 90.46475 | 90.4725 | 0.00775
CHM13/2x100-1M | 93.22665 | 93.2267 | 5e-05
CHM13/2x150-1M | 94.1315 | 94.13815 | 0.00665
CHM13/2x200-1M | 94.41465 | 94.417 | 0.00235
CHM13/2x300-1M | 95.62665 | 95.62605 | -0.0006
rye/2x50-1M | 68.8136 | 68.88975 | 0.07615
rye/2x100-1M | 85.5411 | 85.55745 | 0.01635
rye/2x150-1M | 90.1984 | 90.1907 | -0.0077
rye/2x200-1M | 91.45635 | 91.4566 | 0.00025
rye/2x300-1M | 94.5739 | 94.56905 | -0.00485
maize/2x50-1M | 71.1893 | 71.2683 | 0.079
maize/2x100-1M | 87.1095 | 87.12395 | 0.01445
maize/2x150-1M | 91.6812 | 91.68675 | 0.00555
maize/2x200-1M | 92.91535 | 92.90785 | -0.0075
maize/2x300-1M | 96.71805 | 96.72045 | 0.0024

### CODE REVIEW

**Comment by ksahlin** [comment]
The results look mostly like a significant improvement. I am completely fine with merging these changes it there is not a tremendous overhead in runtime. Did you do any check om how much slower it is?

**Comment by marcelm** [comment]
Ha! The bad results for the 50bp single-end reads were due to a bug: I forgot to re-compute the edit distance when extending the SSW alignments towards the read ends. With that fixed, the results are much better. I have updated the table above.

I also need to change it so that the CIGAR strings are updated just like the edit distance (but this will not change the accuracy). I will do so and then measure impact on runtime (my guess is that it is negligible).

**Comment by ksahlin** [comment]
excellent!

**Comment by marcelm** [comment]
CIGAR is now fixed, and there is no measurable increase in runtime. This is now done.

**Comment by ksahlin** [comment]
Very nice! ok to merge on my end

**Comment by marcelm** [comment]
Merged after adding a changelog entry.

**Pull request merged**
