### PR TITLE
Documentation and changelog

### PR DESCRIPTION
**Pull request by marcelm**

### CODE REVIEW

**Comment by marcelm** [comment]
Note also the extra paragraph in the "Usage" section where I recommend to pipe the output directly into `samtools view` or `samtools sort`.

**Comment by ksahlin** [comment]
I really like the changes you have made to the README!

**Comment by ksahlin** [comment]
I was also debating whether to remove the long "Benchmark" section because it clutters the readme. On the other hand it is nice showing some convincing stats. What do you think?

**Comment by marcelm** [comment]
I didn’t dare suggest it ... I also think it’s a bit long. Maybe move it to a separate file? Perhaps a nice graph can remain in the main README?

**Comment by ksahlin** [comment]
I thrive on 'harsh' feedback, that is how i level up :)

Ok, so then let us move it to a separate file.

**Pull request merged**
