### PR TITLE
Fix invalid alignment starts

### PR DESCRIPTION
**Pull request by marcelm**
This fixes the SAM validation issue #148

### CODE REVIEW

**Comment by marcelm** [comment]
Ahh, nice and now the new test is triggered. I need to look into this later.

**Comment by ksahlin** [comment]
Cool indeed! I looked at the output of the validation script. It reports 10 reads for which score got better (less softclipps in beginning). For these alignments, 9 have MAPQ 60 and 1 have mapq 0.

Tthe reporting script also says `both multimappers, score got better:         4`.

Are some of the multimappers given a score 60 or how do these numbers relate to each other?

**Comment by marcelm** [comment]
The part about fixing #148 was ok, so I reduced the scope of this PR to only fix that. I’ll open a separate PR for the TLEN issue.



> Tthe reporting script also says `both multimappers, score got better: 4`.
> 
> Are some of the multimappers given a score 60 or how do these numbers relate to each other?

That refers to the alignment score (the `AS` tag). That is, a read was a multimapper in the "before" dataset and also in the "after" dataset, but it was mapped to a different position and has a better alignment score at that new position.

**Comment by ksahlin** [comment]
I am probably still misunderstanding something, but let me see if I got this right:

1. A multimapper: A read which maps equally well to more than one location, and this is inferred by a read having MAPQ of 0.
2. `both multimappers,`: means that both the reads in a _read-pair_ were multimappers which means they both had MAPQ 0.
3. `both multimappers, score got better: 4` informs us that four read-pairs aligns better to a location other than their alignment location in strobealign v0.7.1. That is, both the reads within a pair has a new location. 
4. In point 3 the "score" is inferred by the sum of their AS score (?) 

Given the points above would it mean that:
-  strobealign v0.7.1 misclassified (at least) 4 read-pairs as aligning equally well to several locations, but, given the new higher sum of AS scores, it is possible that they have single a unique best location? 
- As for the 10 cases reported separately, these refer to improved AS score for _one of the reads_ in a read pair.  These are separate (not overlapping with) the report of `both multimappers`. 

Are these statements correct?

**Comment by marcelm** [comment]
> I am probably still misunderstanding something, but let me see if I got this right:
> 
>     1. A multimapper: A read which maps equally well to more than one location, and this is inferred by a read having MAPQ of 0.

Correct.

>     2. `both multimappers,`: means that both the reads in a _read-pair_ were multimappers which means they both had MAPQ 0.

No, this refers to single reads. "both" should be read as "both before and after".

I had started to make the `samdiff` script pair-aware but removed that when it got messy and when I realized it wasn’t really necessary for my purposes at the time.

Your points 3 and 4 also assume that "both" means "both reads in a pair", so they are also not correct. Sorry, I will need to re-phrase this in the script to make the meaning of the numbers clearer. The logic computing those numbers is not very complicated at all (see https://github.com/ksahlin/StrobeAlign/blob/main/tests/samdiff.py#L53), I just need to convey this better in the output.

**Comment by ksahlin** [comment]
ah I see, the script is clear. I now understand the reporting limit (10) etc.

**Pull request merged**
